version: '3'
services:
  firesockethub:
    build: .
    container_name: firesockethub
    ports:
      - "127.0.0.1:50050:50050"
      - "127.0.0.1:50055:50055"
    environment:
      - GRPC_SERVER_PORT=50050
      - GIN_SERVER_PORT=50055
    networks:
      - firesocketnet
    restart: always
networks:
  firesocketnet:
